"""add_display_title_to_documents

Revision ID: 2c321d2b33ba
Revises: b371f6ab9b09
Create Date: 2026-08-09 16:26:09.595330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c321d2b33ba'
down_revision: Union[str, None] = 'b371f6ab9b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('display_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'display_title')
    # ### end Alembic commands ###
